#!/bin/bash
#Colours
Yellow='\e[1;33m'
Blue='\e[1;34m'
NC='\e[0m'
#Show warnings:
#echo -e "${Yellow}Warnings:${NC}"
grep -e "WW" /var/log/anaconda/X.log | grep -v "EE" | sed ''/\(WW\)/s//`printf "\033[33mWarning:\033[0m"`/''
#Show information messages:
#echo -e "${Blue}Information:${NC}"
grep -e "II" /var/log/anaconda/X.log | grep -v "++" | sed ''/\(II\)/s//`printf "\033[34mInformation:\033[0m"`/''
